export const mock_solution = [
  {
    week: 1,
    weekSchedule: [
      {
        period: 1,
        games: [
          { teamA: 1, teamB: 2, location: 2 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 2 },
        ],
      },
      {
        period: 2,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 1 },
        ],
      },
    ],
  },
  {
    week: 2,
    weekSchedule: [
      {
        period: 3,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 2 },
        ],
      },
      {
        period: 4,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 3 },
        ],
      },
    ],
  },
];

export const mock_solution1 = [
  {
    week: 1,
    weekSchedule: [
      {
        period: 1,
        games: [
          { teamA: 1, teamB: 2, location: 2 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 2 },
        ],
      },
      {
        period: 2,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 1 },
        ],
      },
    ],
  },
  {
    week: 2,
    weekSchedule: [
      {
        period: 3,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 2 },
        ],
      },
      {
        period: 4,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 3 },
        ],
      },
    ],
  },
  {
    week: 3,
    weekSchedule: [
      {
        period: 3,
        games: [
          { teamA: 1, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 4 },
          { teamA: 5, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 4 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 5, teamB: 2, location: 4 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 5, teamB: 2, location: 4 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 2 },
        ],
      },
      {
        period: 5,
        games: [
          { teamA: 1, teamB: 2, location: 4 },
          { teamA: 5, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 4 },
          { teamA: 5, teamB: 3, location: 2 },
          { teamA: 1, teamB: 2, location: 4 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 5, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 4 },
          { teamA: 5, teamB: 2, location: 1 },
          { teamA: 2, teamB: 3, location: 2 },
          { teamA: 4, teamB: 1, location: 3 },
        ],
      },
    ],
  },
];
